name: Create Release Branch and PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release branch with dummy commit
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          RELEASE_BRANCH="release/$VERSION"

          # Create new branch from latest main
          git checkout -b "$RELEASE_BRANCH" origin/main

          # Add dummy file to ensure a diff and avoid PR rejection
          echo "DO NOT MERGE — Dummy file for release $VERSION" > .release-dummy
          git add .release-dummy
          git commit -m "chore: dummy commit to allow PR [skip ci]"

          # Push release branch
          git push origin "$RELEASE_BRANCH"

      - name: Open pull request from main into release branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          gh pr create \
            --base "release/$VERSION" \
            --head "main" \
            --title "Release $VERSION" \
            --body "Automated PR to merge main into release/$VERSION for deployment."
