name: Create Release Branch and PR

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Name of the release branch (e.g. release/1.2.3)"
        required: true
        type: string

permissions:
  contents: write           # allow pushing new branch
  pull-requests: write      # allow creating PRs (requires repo setting enabled:contentReference[oaicite:0]{index=0})

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main        # ensure we're on latest main

      - name: Create release branch
        run: |
          # Fetch remote to ensure up-to-date and check if branch exists
          git fetch origin main
          git checkout -B "${{ inputs.release_branch }}" origin/main

          # If branch already exists on remote, abort to avoid conflicts
          if git ls-remote --exit-code --heads origin "${{ inputs.release_branch }}"; then
            echo "Release branch already exists on remote. Exiting."
            exit 1
          fi

          # Create an empty commit to ensure branch has a unique history
          git commit --allow-empty -m "chore: start ${{
            inputs.release_branch }} [skip ci]"
          # Push new branch to origin with [skip ci] to avoid triggering workflows:contentReference[oaicite:1]{index=1}
          git push origin "${{ inputs.release_branch }}"
        env:
          GITHUB_AUTHOR: ${{ github.actor }}

      - name: Create pull request from main into release branch
        run: |
          gh pr create \
            --base "${{ inputs.release_branch }}" \
            --head "main" \
            --title "Merge main into ${{
              inputs.release_branch }}" \
            --body "This pull request was automatically created to merge \`main\` into **${{
              inputs.release_branch }}** for release preparation."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
