name: Manual Release Trigger
run-name: Manual Release triggered by ${{ github.actor }}

on:
  workflow_dispatch

jobs:
  CreateReleasePR:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Pull Request from main to release branch
        uses: peter-evans/create-pull-request@v7
        with:
          source: main
          destination: release/${{ steps.version.outputs.version }}
          title: "Release ${{ steps.version.outputs.version }}"
          body: "Automated PR from main to release/${{ steps.version.outputs.version }}"
          commit-message: "chore(release): merge main into release/${{ steps.version.outputs.version }}"