name: Create Release Branch and PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add dummy commit to main
        run: |
          git checkout main
          echo "temp release trigger" > .release-pr-trigger
          git add .release-pr-trigger
          git commit -m "chore: temporary release trigger [skip ci]"
          git push origin main

      - name: Create release branch from updated main
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          RELEASE_BRANCH="release/$VERSION"
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"

      - name: Open pull request (main → release/x.x.x)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          gh pr create \
            --base "release/$VERSION" \
            --head "main" \
            --title "Release $VERSION" \
            --body "Automated PR to merge main into release/$VERSION for deployment."
